on:
  push:
    branches:
    - 'master'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Tag
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: bash .github/ci_tag.sh
