on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker registry login
      run: echo "${{ secrets.REGISTRY_CR }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build docker image
      run: docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF##*/}
    - name: Docker push image
      run: docker push ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF##*/}
