on:
  push:
    branches-ignore:
    - 'master'
    tags-ignore:
    - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Go lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v
  versioncheck:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check versions
      run: bash .github/semver.sh 
